services:
  postgres-dev:
    image: postgres:15
    container_name: trabalho-mps-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8KzpT2VNWE5OJEUS
      POSTGRES_DB: trabalho-mps
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data


volumes:
  postgres_dev_data: